[package]
name = "banker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "banker"
path = "src/banker.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
